### ISSUE TITLE
Enable/disable or backup of dns records

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#87] opened 2013-05-12 20:23 UTC
Reported by: 	batfasturd 	Owned by: 	
Priority: 	minor 	Milestone: 	Later
Component: 	core 	Version: 	2.1.3
Keywords: 		Cc: 	
Description

As an isp we handle dns records for other people, it would be nice to have a check box to enable/disable dns records or have an export/import function to effectively backup and restore dns records.

The issue with this is that the records are stored directly in the powerdns database making it hard to "disable", we'd have to have another cable to store "disabled" records in.

It's a good idea, just not sure the interest people will have in it. If you'd like for this to be coded up, please speak up everyone :)
Changed 3 years ago by ebogdan

Of course I would. I know 3 other that would like it as well. :P

**Comment by SebTM** [comment] 2016-03-07 14:48
Duplicate of #182

**Closed by SebTM** 2016-03-07 14:48 UTC
Labels: feature
