### ISSUE TITLE
Bug: several little but slightly annoying bugs in frontend

### ISSUE THREAD

**Issue by frank42hh** [poweradmin/poweradmin#475] opened 2022-11-28 10:32 UTC
Hi,
First of all, I would like to express my happyness and thankfulness that poweradmin finally managed to live again. I use this for years and when I found out that development has started again, I was very excited.
Despite the fact that I really like the new design, I found some bugs in it and since they all are more like little disturbances, I hope it's ok to put them in a single bugreport. If this is not the case, then my apologies and I'll file them separately.

1) Sorting of IDN domains
When opening the "List zones" overview (list_zones.php) and sorting by "Name", all IDN domains are at the bottom, because the sorting doesn't match on the unicode version of the domain name, but on the punycode - which also means that all domains are collected under the letter x, because the punycode starts with "xn--".

2) Sorting of users
When opening the "List zones" overview and sorting by Owner, then the list is sorted by the username, but the Fullname is displayed. Since they don't need to match, this makes the list not alphabetically sorted, for example if the username "alpha" has the Fullname "ZZ9 Plural Z Alpha", it's listed on top instead on the bottom of the list.

3) Only the first owner of a zone is displayed
On the "List zones" overview, there's only the first owner displayed, even when a zone has multiple owner entries.  Don't know how to solve this, though, since displaying all owner entries could perhaps make column sorting impossible.

4) SOA readonly display breaks row width in zone edit
When the SOA record  is locked, it's displayed in full length, which makes the "Content" column very wide, and this leads to double row size since the "Edit record" and "Delete record" buttons don't fit next to each other anymore

5) User permissions zone_content_edit_own and zone_content_edit_own_as_client unclear
I created a user and gave him a zone. The user template had the zone_content_edit_own_as_client permission set, but without the zone_content_edit_own because I wanted him to edit his zone, but NOT SOA and NS records.
Unfortunately, this seems to work only partially. In his zone the SOA and NS records are locked as expected (e.g. not in editable input fields), and the user can add and edit records, but when trying to delete any records, he gets an error message after sending: "Error: You do not have the permission to delete this record.". The user needs to have zone_content_edit_own  as well to be able to delete records, but that also makes NS records writable.

6) Column titles in users.php don't match column content
When looking at the User administration page, The columns don't match the content. For example the content of the description table row is displayed below "Email address", the email address is displayed under "Template" and the permission template name is displayed under "Enabled".

7) Disable PTR feature does not work
When setting "$iface_add_reverse_record = false;" in config.inc.php, nothing changes. There's still the "Add also reverse record" checkbox besides the "Add record" button.

That's it so far. Everyting's tested with poweradmin v3.3.0 on Debian 11 with php 7.4 fpm.

Well, I hope that' not too much in one ticket, but as said, I'm willing to split this in single tickets if requested.

**Comment by edmondas** [comment] 2022-12-03 20:29
Those observations are very valuable to me, thanks for sharing.

1. It's quite complicated because you'd have to store the domain somewhere in utf8 form to use for sql sorting, or you'd have to rethink the whole mechanism.
2. What's your suggestion, to show username instead?
3. It is possible to do this, but then the list may be too long. Another option to have a popup (tooltip) that displays all owners. Also relating to the sorting issue (2nd point), which user(name) will be used for that?
4. Fixed
5. Fixed
6. Fixed
7. Cannot reproduce, that checkbox hides when setting `$iface_add_reverse_record = false;`

**Comment by frank42hh** [comment] 2022-12-04 13:36
Hi,

> 1. It's quite complicated because you'd have to store the domain somewhere in utf8 form to use for sql sorting, or you'd have to rethink the whole mechanism.
Hmmm, you're right. I don't have an idea yet. I try to think a bit about that.

> 2. What's your suggestion, to show username instead?
I would suggest _adding_ the username, so showing both username and Fullname column. It's perfectly ok to sort by username, but it doesn't make sense IMHO if the username is not visible.

> 3. It is possible to do this, but then the list may be too long. Another option to have a popup (tooltip) that displays all owners. Also relating to the sorting issue (2nd point), which user(name) will be used for that?
Would it perhaps be an option if you add one more layer of n2n connection? E.g. put a "group" between the domain(s) and the owner(s), so you could add exactly one group to any number of domains, and add any number of users to that group. IN that case you could sort by group instead of owners, you could have an unlimited number of users with domain permissions and you would have to add a new user to one group instead of for example 2500 domains when you want to add a new admin. And if you add a new domain, you would just set that one group as permission instead of adding your 742 users one by one.

> 4. Fixed
> 5. Fixed
> 6. Fixed
Great, thanks!

> 7. Cannot reproduce, that checkbox hides when setting `$iface_add_reverse_record = false;`
I might have found the reason for this. At least in my installation I see differences on how config.inc.php is searched for. `lib/Configuration.php` asks for `inc/config.inc.php`, but `inc/toolkit.inc.php` asks for `config.inc.php`. I see several places where the include for the configuration is mixed up with `config.inc.php` and `inc/config.inc.php`. My configuration is in the base directory, because toolkit.inc.php blocks the installation otherwise. After creating a symbolic link from `config.inc.php` into the `inc` subdirectory, the `$iface_add_reverse_record` has been processed. With `config.inc.php` being in base directory only, that setting doesn't get inherited.

I hope that pamphlet makes sense to you :-)

**Comment by edmondas** [comment] 2022-12-05 20:05
Related to 2nd topic, how I changed the zone list view:
![image](https://user-images.githubusercontent.com/9033112/205732577-261b1129-2be6-42ed-9b12-8d9fd50f5138.png)

**Comment by edmondas** [comment] 2022-12-10 08:07
@frank42hh Are you planning on upgrading to PHP 8.x since the 7th version has already been EOL?

**Comment by frank42hh** [comment] 2022-12-13 11:35
first of all, sorry for the late reply, had some rough days full of things to do :-)

> 1. I think it would be good to create a separate ticket for that, sorting is a pretty complex matter, this involves natural sorting as well, and there is another issue with reverse records, so it's not so easy.

I'll try to sum up things and create a new issue for that.

> 2. Full name may not exist, so I did a bit different change - now username will be always visible and in case if there's full name then it will be shown in addition.

Sounds good to me.

> 3. I like your idea about the groups but again it requires changes, so let's have separate ticket for it.

Yep.

> 4. Sounds complex :) by design config.inc.php should be located in `inc` folder. If you're doing clean install then there should be no configuration, because it will be created as a result.

Well, please don't shoot me, but ... 

```
root@vworker03:/var/www/dns.crew-gmbh.de/web# grep config.inc.php inc/toolkit.inc.php 
if (!@include_once('config.inc.php')) {
        error(_('You have to create a config.inc.php!'));
root@vworker03:/var/www/dns.crew-gmbh.de/web# 
```

If I remove the config.inc.php from the basedir, the page aborts with above error message. currently it only works when config.inc.php is in both basedir and inc/. Not sure if this is could be one of the differences between require_once and include_once.


> @frank42hh Are you planning on upgrading to PHP 8.x since the 7th version has already been EOL?

I can switch the php version anytime, 8.x is already installed, but currently inactive for this virtualhost. It was just convenience that I selected v7.

**Comment by edmondas** [comment] 2022-12-20 17:34
I was able to implement 3rd bullet - showing of all owners:

**Comment by edmondas** [comment] 2022-12-25 19:04
I am closing this ticket. There are two related issues, #481 and #488

**Closed by edmondas** 2022-12-25 19:04 UTC
Labels: enhancement
