### ISSUE TITLE
An error occurred while executing the SQL statement. Please contact an Administrator and report the problem.

### ISSUE THREAD

**Issue by 9craig** [poweradmin/poweradmin#324] opened 2017-09-10 03:32 UTC
Hi,

I have the same problem discussed in issue #187 . (See below for output.) I see that it was supposedly fixed, but it's still broken in 2.1.7 in at least one case.

If I have previously viewed "List zones" and sorted the list by the number of records, and *then* I "Search zones and records", I get the same error. If I go back to "List zones" and re-sort based on another field, then do another search, the search succeeds.

Craig

````
An error occurred while executing the SQL statement. Please contact an Administrator and report the problem.
The following query generated an error:

SELECT
			domains.id AS zid,

			domains.name AS name,

			domains.type AS type,

			domains.master AS master,

                        zones.owner AS owner
			
FROM domains,
 zones,
 users 
			
WHERE  domains.name LIKE '%niner%' 
AND zones.domain_id = domains.id 
AND users.id = '1'
                        
ORDER BY count_records

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'count_records' in 'order clause'
````

**Comment by edmondas** [comment] 2022-01-09 15:31
I could not reproduce the problem with the latest code. Closing the ticket.

**Closed by edmondas** 2022-01-09 15:31 UTC
Labels: bug, unconfirmed
