### ISSUE TITLE
After fresh install can not login to admin

### ISSUE THREAD

**Issue by 4ndyhidayat** [poweradmin/poweradmin#574] opened 2024-07-30 15:30 UTC
after install I can not login to dashboard menu, no error in the log either other log. I though it's php extension, but none of them. Anyone?

**Comment by GamingForLive** [comment] 2024-08-05 22:41
Same here thought i was crazy at first but i did the setup 3 times so far and also whats weird is that the setup will ask you for the hostname of the database and then will make a user with username@dbhostname wich would restrict the login to the database to the database itself afaik weird imop

**Comment by edmondas** [comment] 2024-08-06 04:54
@4ndyhidayat Are you having the same problems with the latest version?. Do you use MariaDB or a similar database (such as MySQL)? Let's check if this is related to the database user referenced by @GamingForLive

**Comment by 4ndyhidayat** [comment] 2024-08-06 04:59
Yess... I'll check it again later. btw I'm using FreeBSD and installed using pkg. How can I use mariadb instead of mysql. Because when I installed PowerDNS, the default is mysql client. Any suggest? *it works when I used 3.6.1 version (no issue like I post here)

**Comment by GamingForLive** [comment] 2024-08-06 05:03
Afaik the mysql connector also works with mariadb databases

**Comment by edmondas** [comment] 2024-08-06 06:54
@4ndyhidayat You can use any MySQL-like client on your machine. Later, I'll try to review the changes between 3.6.1 and the latest code.

**Comment by edmondas** [comment] 2024-08-06 15:50
@GamingForLive The problem with creating PowerAdmin database users has been fixed, I have given wider access as it can now be installed on different hosts. See commit 399b70e

**Comment by GamingForLive** [comment] 2024-08-06 16:53
👍Great thanks for fixxing that so fast i dont think that that is the root cause but i will try it later once i got some free time

**Comment by 4ndyhidayat** [comment] 2024-08-06 20:32
Awesome... thank you so much for fixing this. I'll try again later...

**Comment by edmondas** [comment] 2024-08-12 05:32
@4ndyhidayat I have another idea, if you could take screenshots of the installation and email me the details of how you do it (you can find it in my GitHub profile), that would be helpful. Maybe I am missing something important.

**Comment by 4ndyhidayat** [comment] 2024-08-12 06:29
> Afaik the mysql connector also works with mariadb databases

Yess... Correct. It works now with 7 replication DB using MariaDB... A little bit tricky installed the PowerDNS using MariaDB under FreeBSD using pkg/ports. But no issue using Linux... 

My 7 NS using PowerDNS with PowerAdmin under FreeBSD 13.3-Stable :

satoe.toedjoeh.com
doea.toedjoeh.com
tiga.toedjoeh.com
empattoedjoeh.com
lima.toedjoeh.com
enam.toedjoeh.com
toedjoeh.toedjoeh.com

**Comment by edmondas** [comment] 2024-08-15 11:50
One of the possible problems with failed login or unable to login (no error message visible) could be related to your installation not having an SSL certificate (perhaps it's running under plain http).

For reference: https://github.com/poweradmin/poweradmin/issues/577#issuecomment-2291116264

**Comment by edmondas** [comment] 2024-08-15 12:11
I'm closing this ticket if there are other issues then create new or something related to this topic then reopen this one

**Closed** 2024-08-15 12:11 UTC
Labels: bug
