### ISSUE TITLE
update zones using template fails in tag version 2.1.7

### ISSUE THREAD

**Issue by geek4unix** [poweradmin/poweradmin#388] opened 2020-12-14 12:26 UTC
When I am using a template , i modify it and commit the changes, the press Update Zones, which results in :

<img width="1516" alt="Screenshot 2020-12-14 at 13 25 15" src="https://user-images.githubusercontent.com/6726149/102081090-ef96c880-3e0f-11eb-86a9-43cadc671d8d.png">

**Comment by edmondas** [comment] 2020-12-14 13:27
@geek4unix could you check if the issue is still in the master version?

**Comment by geek4unix** [comment] 2020-12-14 14:16
Yes works ok on master @edmondas

**Comment by edmondas** [comment] 2021-12-28 09:10
It seems that it's fixed on master, so closing it for now.

**Closed by edmondas** 2021-12-28 09:10 UTC
Labels: bug
