### ISSUE TITLE
[SERIAL] Not working in Zone Template for SOA records.

### ISSUE THREAD

**Issue by benphelps** [poweradmin/poweradmin#260] opened 2015-11-27 03:00 UTC
When adding an SOA to a Zone Template, [SERIAL] is not used and the value is always blank

Steps to recreate:
1. Create Zone Template
2. Add SOA record to Zone Template, using [SERIAL] in zone content.
3. Add new Template to a Zone
4. Content field is blank on newly created record.

**Comment by SebTM** [comment] 2016-02-22 07:06
For me it's working since the SOA content follows the required structure. Generally I would think the SOA concept of poweradmin should be refactored, since I know there can only be one SOA for every zone.

**Comment by edmondas** [comment] 2022-01-08 18:04
I'm closing the ticket since I can't reproduce the issue.

**Closed by edmondas** 2022-01-08 18:04 UTC
Labels: question, invalid
